### ISSUE TITLE
leetcode-tool meta 1189 会报错

### ISSUE THREAD

**Issue by Mary526** [zcong1993/algo-go#1]
**问题：在查询 / 新建问题1189时命令行抛异常了，请作者有空看下是哪里操作的问题呀？非常感谢**
```
leetcode-tool meta 1189
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1395755]

goroutine 1 [running]:
main.showMeta(0x7ffeefbffaf3, 0x4)
	/home/runner/work/leetcode-tool/leetcode-tool/cmd/main.go:43 +0x95
main.main()
	/home/runner/work/leetcode-tool/leetcode-tool/cmd/main.go:60 +0x289
```
![报错截图](https://user-images.githubusercontent.com/15365812/130386682-8694af00-71b2-498c-95e0-5070a2cf07bb.png)

环境：
- macOS Big Sur 版本11.4
- leetcode-tool 版本 0.4.0
- 刷题语言 javascript
![image](https://user-images.githubusercontent.com/15365812/130386774-1b2e7c8d-93e8-4bd8-8858-3e2cb914bdcb.png)

**Comment by zcong1993** [comment]
应该是 leetcode 数据结构变了, 我有空看看

**Comment by zcong1993** [comment]
更新一下版本, 然后查看文档 https://github.com/zcong1993/leetcode-tool#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by Mary526** [comment]
怎么更新呢，我看homebrew上还是0.4.0版本

**Comment by zcong1993** [comment]
> 怎么更新呢，我看homebrew上还是0.4.0版本

brew upgrade leetcode-tool

**Comment by Mary526** [comment]
谢谢回复，我的意思是brew上工具版本还是0.4.0呢
![image](https://user-images.githubusercontent.com/15365812/130421438-f876d0b1-9f92-4290-a12f-7b86bcc5cb7e.png)

**Comment by zcong1993** [comment]
> 谢谢回复，我的意思是brew上工具版本还是0.4.0呢
> ![image](https://user-images.githubusercontent.com/15365812/130421438-f876d0b1-9f92-4290-a12f-7b86bcc5cb7e.png)

brew update 下, 我这边没问题的

```
ζ brew info leetcode-tool
zcong1993/tap/leetcode-tool: stable 0.4.1
一个让你更方便刷题的工具
https://github.com/zcong1993/leetcode-tool
/usr/local/Cellar/leetcode-tool/0.4.1 (5 files, 7.6MB) *
  Built from source on 2021-08-23 at 13:36:43
From: https://github.com/zcong1993/homebrew-tap/blob/HEAD/Formula/leetcode-tool.rb
```
